datasets:
  data_path: data/dataset.csv
  imbalance_strategy: undersample
  majority_class: 1
  minority_class: 0
  random_state: 23
  test_size: 0.1
  undersample_n_samples: 220
encoding:
  scales:
  - 3
  - 4
  - 5
  type: adaptive_word2vec
  word2vec:
    min_count: 1
    vector_size: 128
    window: 5
    workers: 2
models:
  lstm:
    dense_units_1: 50
    dense_units_2: 50
    dropout_rate: 0.3
    lstm_units: 50
    output_units: 1
    use_scale_attention: true
  type: lstm
paths:
  outputs_dir: outputs/
  weights_dir: weights/
training:
  batch_size: 32
  epochs: 100
  optimizer: adam
